# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f33cbf0ff8464dcfb4f33d1a386a7ea9250d8fa4d95e9c08c7a19ae35169ca90e2b087cba3b5419edb66ef84ecc1920cca1d0844b3df2e7a2c074b732ef8e5d6

test:
  secret_key_base: 2fbb8f4e958f229e1c3d9118d2a1cea946a1658707e97ac8d5f171bd1311bbbcb0c704b65340bc35510b5910eecdd93fd46f61ef518adc4c91defb457c17e012

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
